version: "3"

services: 
  db:
    image: mysql:5.7
    container_name: hw09_jdbc
    ports: 
      - "3310:3306"
    environment:
       MYSQL_RANDOM_ROOT_PASSWORD: 1
       MYSQL_DATABASE: hw09
       MYSQL_USER: dbuser
       MYSQL_PASSWORD: dbuserpassword
       MYSQL_ALLOW_EMPTY_PASSWORD: "no"
    volumes: 
      - ./db:/var/lib/mysql
      - ./_MySQL_Init_Script:/docker-entrypoint-initdb.d
    restart: "no"

