version: "3"

services: 
  db10:
    image: mysql:5.7
    container_name: hw10_jdbc
    ports: 
      - "3309:3306"
    environment:
       MYSQL_RANDOM_ROOT_PASSWORD: 1
       MYSQL_DATABASE: hw10
       MYSQL_USER: dbuser
       MYSQL_PASSWORD: dbuserpassword
       MYSQL_ALLOW_EMPTY_PASSWORD: "no"
    volumes: 
      - ./db:/var/lib/mysql
      - ./_MySQL_Init_Script:/docker-entrypoint-initdb.d
    restart: "no"

