USE hw10;

CREATE TABLE IF NOT EXISTS Address (
 id BIGINT(20) NOT NULL AUTO_INCREMENT,
 street VARCHAR(255),
 CONSTRAINT address_pk PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS Phone (
 id BIGINT(20) NOT NULL AUTO_INCREMENT,
 number VARCHAR(255),
 CONSTRAINT phone_pk PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS User (
 id BIGINT(20) NOT NULL AUTO_INCREMENT,
 name VARCHAR(255),
 age INT(3),
 phone_id BIGINT(20),
 address_id BIGINT(20),
 CONSTRAINT users_pk PRIMARY KEY (id),
 FOREIGN KEY(phone_id) REFERENCES Phone(id)
);
